spring.application.name=kritika-url-shortener

app.base-url=https://kritika-url-shortener-production.up.railway.app
app.default-expiry-in-days=30
app.validate-original-url=true
app.page-size=10

spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.docker.compose.enabled=false