spring.application.name=kritika-url-shortener

app.base-url=https://kritika-url-shortener-production.up.railway.app
app.default-expiry-in-days=30
app.validate-original-url=true
app.page-size=10

spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.docker.compose.enabled=false